<?php

namespace CoreBundle\Repository;

/**
 * WallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWallByUserAuth()
    {
        return $this->createQueryBuilder('i')
            ->where('i.user = :user');
    }
}
