core_wall:
    resource: "@CoreBundle/Resources/config/routing/wall.yml"
    prefix:   /{_locale}/wall

admin_core_user:
    resource: "@CoreBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

# We override this part of the routing
hwi_oauth_connect:
     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
     prefix: /connect

twitter_login:
    pattern: /connect/check-twitter

twitter_index:
    path:     /{_locale}/twitter
    defaults: { _controller: CoreBundle:Twitter:index }
    methods:  [GET, POST]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
